--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.fight_pb')

STARTFIGHT = protobuf.Descriptor();
STARTFIGHT_ERRORCODE_FIELD = protobuf.FieldDescriptor();
STARTFIGHT_VERSION_FIELD = protobuf.FieldDescriptor();
FIGHTRESULT = protobuf.Descriptor();
FIGHTRESULT_NAME_FIELD = protobuf.FieldDescriptor();
FIGHTRESULT_CONTENT_FIELD = protobuf.FieldDescriptor();
ENTERFIGHT = protobuf.Descriptor();
ENTERFIGHT_NAME_FIELD = protobuf.FieldDescriptor();
ENTERFIGHT_CONTENT_FIELD = protobuf.FieldDescriptor();

STARTFIGHT_ERRORCODE_FIELD.name = "errorCode"
STARTFIGHT_ERRORCODE_FIELD.full_name = ".msg.StartFight.errorCode"
STARTFIGHT_ERRORCODE_FIELD.number = 1
STARTFIGHT_ERRORCODE_FIELD.index = 0
STARTFIGHT_ERRORCODE_FIELD.label = 1
STARTFIGHT_ERRORCODE_FIELD.has_default_value = false
STARTFIGHT_ERRORCODE_FIELD.default_value = 0
STARTFIGHT_ERRORCODE_FIELD.type = 5
STARTFIGHT_ERRORCODE_FIELD.cpp_type = 1

STARTFIGHT_VERSION_FIELD.name = "version"
STARTFIGHT_VERSION_FIELD.full_name = ".msg.StartFight.version"
STARTFIGHT_VERSION_FIELD.number = 2
STARTFIGHT_VERSION_FIELD.index = 1
STARTFIGHT_VERSION_FIELD.label = 1
STARTFIGHT_VERSION_FIELD.has_default_value = false
STARTFIGHT_VERSION_FIELD.default_value = 0.0
STARTFIGHT_VERSION_FIELD.type = 2
STARTFIGHT_VERSION_FIELD.cpp_type = 6

STARTFIGHT.name = "StartFight"
STARTFIGHT.full_name = ".msg.StartFight"
STARTFIGHT.nested_types = {}
STARTFIGHT.enum_types = {}
STARTFIGHT.fields = {STARTFIGHT_ERRORCODE_FIELD, STARTFIGHT_VERSION_FIELD}
STARTFIGHT.is_extendable = false
STARTFIGHT.extensions = {}
FIGHTRESULT_NAME_FIELD.name = "name"
FIGHTRESULT_NAME_FIELD.full_name = ".msg.FightResult.name"
FIGHTRESULT_NAME_FIELD.number = 1
FIGHTRESULT_NAME_FIELD.index = 0
FIGHTRESULT_NAME_FIELD.label = 1
FIGHTRESULT_NAME_FIELD.has_default_value = false
FIGHTRESULT_NAME_FIELD.default_value = ""
FIGHTRESULT_NAME_FIELD.type = 9
FIGHTRESULT_NAME_FIELD.cpp_type = 9

FIGHTRESULT_CONTENT_FIELD.name = "content"
FIGHTRESULT_CONTENT_FIELD.full_name = ".msg.FightResult.content"
FIGHTRESULT_CONTENT_FIELD.number = 2
FIGHTRESULT_CONTENT_FIELD.index = 1
FIGHTRESULT_CONTENT_FIELD.label = 1
FIGHTRESULT_CONTENT_FIELD.has_default_value = false
FIGHTRESULT_CONTENT_FIELD.default_value = ""
FIGHTRESULT_CONTENT_FIELD.type = 9
FIGHTRESULT_CONTENT_FIELD.cpp_type = 9

FIGHTRESULT.name = "FightResult"
FIGHTRESULT.full_name = ".msg.FightResult"
FIGHTRESULT.nested_types = {}
FIGHTRESULT.enum_types = {}
FIGHTRESULT.fields = {FIGHTRESULT_NAME_FIELD, FIGHTRESULT_CONTENT_FIELD}
FIGHTRESULT.is_extendable = false
FIGHTRESULT.extensions = {}
ENTERFIGHT_NAME_FIELD.name = "name"
ENTERFIGHT_NAME_FIELD.full_name = ".msg.EnterFight.name"
ENTERFIGHT_NAME_FIELD.number = 1
ENTERFIGHT_NAME_FIELD.index = 0
ENTERFIGHT_NAME_FIELD.label = 1
ENTERFIGHT_NAME_FIELD.has_default_value = false
ENTERFIGHT_NAME_FIELD.default_value = ""
ENTERFIGHT_NAME_FIELD.type = 9
ENTERFIGHT_NAME_FIELD.cpp_type = 9

ENTERFIGHT_CONTENT_FIELD.name = "content"
ENTERFIGHT_CONTENT_FIELD.full_name = ".msg.EnterFight.content"
ENTERFIGHT_CONTENT_FIELD.number = 2
ENTERFIGHT_CONTENT_FIELD.index = 1
ENTERFIGHT_CONTENT_FIELD.label = 1
ENTERFIGHT_CONTENT_FIELD.has_default_value = false
ENTERFIGHT_CONTENT_FIELD.default_value = ""
ENTERFIGHT_CONTENT_FIELD.type = 9
ENTERFIGHT_CONTENT_FIELD.cpp_type = 9

ENTERFIGHT.name = "EnterFight"
ENTERFIGHT.full_name = ".msg.EnterFight"
ENTERFIGHT.nested_types = {}
ENTERFIGHT.enum_types = {}
ENTERFIGHT.fields = {ENTERFIGHT_NAME_FIELD, ENTERFIGHT_CONTENT_FIELD}
ENTERFIGHT.is_extendable = false
ENTERFIGHT.extensions = {}

EnterFight = protobuf.Message(ENTERFIGHT)
FightResult = protobuf.Message(FIGHTRESULT)
StartFight = protobuf.Message(STARTFIGHT)

