--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.home_pb')

HOME = protobuf.Descriptor();
HOME_ADDRESS_FIELD = protobuf.FieldDescriptor();

HOME_ADDRESS_FIELD.name = "address"
HOME_ADDRESS_FIELD.full_name = ".msg.Home.address"
HOME_ADDRESS_FIELD.number = 1
HOME_ADDRESS_FIELD.index = 0
HOME_ADDRESS_FIELD.label = 2
HOME_ADDRESS_FIELD.has_default_value = false
HOME_ADDRESS_FIELD.default_value = 0
HOME_ADDRESS_FIELD.type = 5
HOME_ADDRESS_FIELD.cpp_type = 1

HOME.name = "Home"
HOME.full_name = ".msg.Home"
HOME.nested_types = {}
HOME.enum_types = {}
HOME.fields = {HOME_ADDRESS_FIELD}
HOME.is_extendable = false
HOME.extensions = {}

Home = protobuf.Message(HOME)

